spring.application.name=inventario-service
server.port=8084

logging.level.root=INFO
logging.level.org.hibernate.SQL=INFO

spring.datasource.url=jdbc:postgresql://localhost:5432/inventario_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50

spring.output.ansi.enabled=always

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration