services:

  eureka-server:
    build: ./eureka_server
    container_name: eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api_gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka

  # BASES DE DATOS

  mysql-sucursal:
    image: mysql:8
    container_name: mysql-sucursal
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sucursal_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root

  mysql-ubicacion:
    image: mysql:8
    container_name: mysql-ubicacion
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ubicacion_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
  mysql-producto:
    image: mysql:8
    container_name: mysql-producto
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: producto_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root

  mysql-venta:
    image: mysql:8
    container_name: mysql-venta
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: venta_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root

  mysql-usuario:                                 # <--- ¡NUEVA BASE DE DATOS!
    image: mysql:8
    container_name: mysql-usuario
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: usuario_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root

  postgres-inventario:
    image: postgres:15
    container_name: postgres-inventario
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: inventario_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  postgres-abastecimiento:
    image: postgres:15
    container_name: postgres-abastecimiento
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_DB: abastecimiento_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  # MICROSERVICIOS
    
  sucursal-service:
    build: ./sucursal_service
    container_name: sucursal-service
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
      - mysql-sucursal
    environment:
      DB_URL: jdbc:mysql://mysql-sucursal:3306/sucursal_db
      DB_USERNAME: admin
      DB_PASSWORD: admin
      EUREKA_URL: http://eureka-server:8761/eureka

  ubicacion-service:
    build: ./ubicacion_service
    container_name: ubicacion-service
    ports:
      - "8087:8087"
    depends_on:
      - eureka-server
      - mysql-ubicacion
    environment:
      DB_URL: jdbc:mysql://mysql-ubicacion:3306/ubicacion_db
      DB_USERNAME: admin
      DB_PASSWORD: admin
      EUREKA_URL: http://eureka-server:8761/eureka

  producto-service:
    build: ./producto_service
    container_name: producto-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - mysql-producto
    environment:
      DB_URL: jdbc:mysql://mysql-producto:3306/producto_db
      DB_USERNAME: admin
      DB_PASSWORD: admin
      EUREKA_URL: http://eureka-server:8761/eureka

  venta-service:
    build: ./venta_service
    container_name: venta-service
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
      - mysql-venta
    environment:
      DB_URL: jdbc:mysql://mysql-venta:3306/venta_db
      DB_USERNAME: admin
      DB_PASSWORD: admin
      EUREKA_URL: http://eureka-server:8761/eureka

  usuario-service:                              # <--- ¡MODIFICADO A MYSQL!
    build: ./usuario_service
    container_name: usuario-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - mysql-usuario
    environment:
      DB_URL: jdbc:mysql://mysql-usuario:3306/usuario_db?allowPublicKeyRetrieval=true&useSSL=false
      DB_USERNAME: admin
      DB_PASSWORD: admin
      EUREKA_URL: http://eureka-server:8761/eureka

  inventario-service:
    build: ./inventario_service
    container_name: inventario-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - postgres-inventario
    environment:
      DB_URL: jdbc:postgresql://postgres-inventario:5432/inventario_db
      DB_USERNAME: admin
      DB_PASSWORD: admin
      EUREKA_URL: http://eureka-server:8761/eureka

  abastecimiento-service:
    build: ./abastecimiento_service
    container_name: abastecimiento-service
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - postgres-abastecimiento
    environment:
      DB_URL: jdbc:postgresql://postgres-abastecimiento:5432/abastecimiento_db
      DB_USERNAME: admin
      DB_PASSWORD: admin
      EUREKA_URL: http://eureka-server:8761/eureka

networks:
  default:
    name: microservicios-network
  