server:
    port: 8082

spring:
    application:
        name: usuario-service
    profiles:
        active: dev
    output:
        ansi:
            enabled: ALWAYS

    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

    flyway:
        enabled: true
        locations: classpath:db/migration

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URL}

springdoc:
    api-docs:
        enabled: true   
    swagger-ui:
        enabled: true
        path: /doc/swagger-ui

logging:
    file:
        name: logs/usuario.log
        path: logs
    level:
        org:
            springframework:
                web: DEBUG
            hibernate:
                SQL: INFO
        root: INFO
    logback:
        rollingpolicy:
            max-file-size: 10MB
            max-history: 30

---
# PERFIL DE PRUEBAS (test) -> Base de datos mágica en memoria RAM
spring:
  config:
    activate:
      on-profile: test

  datasource:
    # Esto crea una BD PostgreSQL simulada en la memoria RAM
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  # Apagamos Flyway en los tests para que no intente aplicar migraciones reales en la RAM
  flyway:
    enabled: false