spring.application.name=usuario-service

server.port=8082

logging.file.name=logs/sucursal.log
logging.file.path=logs
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.root=INFO

# Usa colores ANSI en la consola siempre
spring.output.ansi.enabled=ALWAYS

spring.datasource.url=jdbc:oracle:thin:@bdusuario_high?TNS_ADMIN=C:/Users/bobip/Documents/Inventario-y-Logistica/usuario_service/Wallet_bdUsuario
spring.datasource.username=BD_USUARIO
spring.datasource.password=Duocuc12345.
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration