server:
    port: 8082

spring:
    application:
        name: usuario-service
    profiles:
        active: dev
    output:
        ansi:
            enabled: ALWAYS

    datasource:
        url: jdbc:oracle:thin:@bdusuario_high?TNS_ADMIN=C:/Users/bobip/Documents/Inventario-y-Logistica/usuario_service/Wallet_bdUsuario
        username: BD_USUARIO
        password: Duocuc12345.

    flyway:
        enabled: true
        locations: classpath:db/migration

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

springdoc:
    api-docs:
        enabled: true   
    swagger-ui:
        enabled: true
        path: /doc/swagger-ui

logging:
    file:
        name: logs/usuario.log
        path: logs
    level:
        org:
            springframework:
                web: DEBUG
            hibernate:
                SQL: INFO
        root: INFO
    logback:
        rollingpolicy:
            max-file-size: 10MB
            max-history: 30