CREATE TABLE venta (
    venta_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cod_venta BIGINT NOT NULL UNIQUE,
    cod_sucursal VARCHAR(30) NOT NULL,
    run VARCHAR(10) NOT NULL,
    fecha_venta DATE NOT NULL DEFAULT CURRENT_DATE
);