-- POBLAR TABLA REGION
INSERT INTO region(cod_region, descripcion) VALUES('15', 'REGIÓN DE ARICA Y PARINACOTA');
INSERT INTO region(cod_region, descripcion) VALUES('1', 'REGIÓN DE TARAPACÁ');
INSERT INTO region(cod_region, descripcion) VALUES('2', 'REGIÓN DE ANTOFAGASTA');
INSERT INTO region(cod_region, descripcion) VALUES('3', 'REGIÓN DE ATACAMA');
INSERT INTO region(cod_region, descripcion) VALUES('4', 'REGIÓN DE COQUIMBO');
INSERT INTO region(cod_region, descripcion) VALUES('5', 'REGIÓN DE VALPARAÍSO');
INSERT INTO region(cod_region, descripcion) VALUES('RM', 'REGIÓN DE METROPOLITANA DE SANTIAGO');
INSERT INTO region(cod_region, descripcion) VALUES('6' ,'REGIÓN DE DEL LIBERTADOR GENERAL DE BERNARDO O''HIGGINS');
INSERT INTO region(cod_region, descripcion) VALUES('7' ,'REGIÓN DEL MAULE');
INSERT INTO region(cod_region, descripcion) VALUES('16', 'REGIÓN DEL ÑUBLE');
INSERT INTO region(cod_region, descripcion) VALUES('8', 'REGIÓN DEL BIOBIO');
INSERT INTO region(cod_region, descripcion) VALUES('9', 'REGIÓN DE LA ARAUCANÍA');
INSERT INTO region(cod_region, descripcion) VALUES('14', 'REGIÓN DE LOS RÍOS');
INSERT INTO region(cod_region, descripcion) VALUES('10', 'REGIÓN DE LOS LAGOS');
INSERT INTO region(cod_region, descripcion) VALUES('11', 'REGIÓN DE AYSÉN DEL GENERAL CARLOS IBÁÑEZ DEL CAMPO');
INSERT INTO region(cod_region, descripcion) VALUES('12', 'REGIÓN DE MAGALLANES Y DE LA ANTÁRTICA CHILENA');

-- POBLAR TABLA COMUNA
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(1, '15', 'ARICA');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(2, '15', 'PUTRE');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(3, '15', 'CAMARONES');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(4, '1', 'IQUIQUE');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(5, '1', 'POZO ALMONTE');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(6, '2', 'ANTOFAGASTA');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(7, '2', 'CALAMA');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(8, '2', 'TOCOPILLA');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(9, '3', 'COPIAPÓ');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(10, '4', 'LA SERENA');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(11, '4', 'COQUIMBO');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(12, '5', 'VIÑA DEL MAR');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(13, '5', 'VALPARAÍSO');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(14, 'RM', 'SANTIAGO');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(15, 'RM', 'PUENTE ALTO');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(16, 'RM', 'MAIPÚ');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(17, '6', 'RANCAGUA');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(18, '7', 'TALCA');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(19, '16', 'CHILLÁN');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(20, '13', 'CONCEPCIÓN');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(21, '13', 'LOS ÁNGELES');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(22, '9', 'TEMUCO');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(23, '9', 'ANGOL');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(24, '14', 'VALDIVIA');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(25, '10', 'PUERTO MONTT');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(26, '10', 'OSORNO');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(27, '11', 'COYHAIQUE');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(28, '11', 'PUERTO AYSÉN');
INSERT INTO comuna(cod_comuna, region, descripcion) VALUES(29, '12', 'PUNTA ARENAS');