-- POBLAR TABLA REGION
INSERT INTO region(descripcion) VALUES('REGIÓN DE ARICA Y PARINACOTA');
INSERT INTO region(descripcion) VALUES('REGIÓN DE TARAPACÁ');
INSERT INTO region(descripcion) VALUES('REGIÓN DE ANTOFAGASTA');
INSERT INTO region(descripcion) VALUES('REGIÓN DE ATACAMA');
INSERT INTO region(descripcion) VALUES('REGIÓN DE COQUIMBO');
INSERT INTO region(descripcion) VALUES('REGIÓN DE VALPARAÍSO');
INSERT INTO region(descripcion) VALUES('REGIÓN DE METROPOLITANA DE SANTIAGO');
INSERT INTO region(descripcion) VALUES('REGIÓN DE DEL LIBERTADOR GENERAL DE BERNARDO O''HIGGINS');
INSERT INTO region(descripcion) VALUES('REGIÓN DEL MAULE');
INSERT INTO region(descripcion) VALUES('REGIÓN DEL ÑUBLE');
INSERT INTO region(descripcion) VALUES('REGIÓN DEL BIOBIO');
INSERT INTO region(descripcion) VALUES('REGIÓN DE LA ARAUCANÍA');
INSERT INTO region(descripcion) VALUES('REGIÓN DE LOS RÍOS');
INSERT INTO region(descripcion) VALUES('REGIÓN DE LOS LAGOS');
INSERT INTO region(descripcion) VALUES('REGIÓN DE AYSÉN DEL GENERAL CARLOS IBÁÑEZ DEL CAMPO');
INSERT INTO region(descripcion) VALUES('REGIÓN DE MAGALLANES Y DE LA ANTÁRTICA CHILENA');

-- POBLAR TABLA COMUNA
INSERT INTO comuna(region, descripcion) VALUES(1, 'ARICA');
INSERT INTO comuna(region, descripcion) VALUES(1, 'PUTRE');
INSERT INTO comuna(region, descripcion) VALUES(1, 'CAMARONES');
INSERT INTO comuna(region, descripcion) VALUES(2, 'IQUIQUE');
INSERT INTO comuna(region, descripcion) VALUES(2, 'POZO ALMONTE');
INSERT INTO comuna(region, descripcion) VALUES(3, 'ANTOFAGASTA');
INSERT INTO comuna(region, descripcion) VALUES(3, 'CALAMA');
INSERT INTO comuna(region, descripcion) VALUES(3, 'TOCOPILLA');
INSERT INTO comuna(region, descripcion) VALUES(4, 'COPIAPÓ');
INSERT INTO comuna(region, descripcion) VALUES(5, 'LA SERENA');
INSERT INTO comuna(region, descripcion) VALUES(5, 'COQUIMBO');
INSERT INTO comuna(region, descripcion) VALUES(6, 'VIÑA DEL MAR');
INSERT INTO comuna(region, descripcion) VALUES(6, 'VALPARAÍSO');
INSERT INTO comuna(region, descripcion) VALUES(6, 'IQUIQUE');
INSERT INTO comuna(region, descripcion) VALUES(7, 'SANTIAGO');
INSERT INTO comuna(region, descripcion) VALUES(7, 'PUENTE ALTO');
INSERT INTO comuna(region, descripcion) VALUES(7, 'MAIPÚ');
INSERT INTO comuna(region, descripcion) VALUES(8, 'RANCAGUA');
INSERT INTO comuna(region, descripcion) VALUES(9, 'TALCA');
INSERT INTO comuna(region, descripcion) VALUES(10, 'CHILLÁN');
INSERT INTO comuna(region, descripcion) VALUES(11, 'CONCEPCIÓN');
INSERT INTO comuna(region, descripcion) VALUES(11, 'LOS ÁNGELES');
INSERT INTO comuna(region, descripcion) VALUES(12, 'TEMUCO');
INSERT INTO comuna(region, descripcion) VALUES(12, 'ANGOL');
INSERT INTO comuna(region, descripcion) VALUES(13, 'VALDIVIA');
INSERT INTO comuna(region, descripcion) VALUES(14, 'PUERTO MONTT');
INSERT INTO comuna(region, descripcion) VALUES(14, 'OSORNO');
INSERT INTO comuna(region, descripcion) VALUES(15, 'COYHAIQUE');
INSERT INTO comuna(region, descripcion) VALUES(15, 'PUERTO AYSÉN');
INSERT INTO comuna(region, descripcion) VALUES(16, 'PUNTA ARENAS');