spring.application.name=sucursal_service

server.port=8082

# FALTAN LOS LOGGS DE LOGGER

# Usa colores ANSI en la consola siempre
spring.output.ansi.enabled=ALWAYS

spring.datasource.url=jdbc:mysql://localhost:3306/bd_sucursal
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration