CREATE TABLE usuario (
    usuario_id NUMBER GENEREATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    numrun NUMBER NOT NULL,
    dvrun VARCHAR2(1) NOT NULL,
    appaterno VARCHAR2(20) NOT NULL,
    apmaterno VARCHAR2(20) NOT NULL,
    nombres VARCHAR2(30) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    direccion VARCHAR2(100),
    region_id  VARCHAR2(30) NOT NULL,
    telefono VARCHAR2(12) NOT NULL,
    correo VARCHAR2(50) CONSTRAINT USUARIO_CORREO_UN UNIQUE NOT NULL,
    profesion VARCHAR2(25) NOT NULL,
    sucursal_id NUMBER NOT NULL,

    CONSTRAINT USUARIO_PK PRIMARY KEY (usuario_id)
);